---
title: "PCA analysis exploratory"
author: "Rene Welch"
output:
  html_document:
    toc: yes
    theme: simplex
  pdf_document:
    toc: yes
---

```{r load,include=FALSE,echo=FALSE,eval=TRUE}
library(tidyverse)
library(here)
library(viridis)
library(ggtech)
library(hexbin)
library(gridExtra)
library(forcats)
library(scales)
library(knitr)
library(ggrepel)
library(pheatmap)
library(ggjoy)
library(clusterProfiler)
pal = viridis(1e3, option = "D")

## parameters
thr = 1
fdr = .01

theme_set(theme_minimal() + 
            theme(legend.position = "top",
                  axis.text = element_text(size = 8),
                  axis.title = element_text(size = 12)))

knitr::opts_chunk$set(eval = TRUE,
                      echo = FALSE,
                      include = TRUE,
                      warning = FALSE,
                      message = FALSE
                    )

load2env = function(file,env = new.env()){load(file,envir = env); env}
fig3 = load2env(here("apps/Fig3_dashboad/fig3data.RData"))
fig5 = load2env(here("apps/Fig5_dashboard/fig5data.RData"))

fig3$alignment = fig3$alignment %>% 
  mutate(
    treat = if_else(treat == "None","none","MC") %>% 
      factor(levels = c("MC","none")),
    cell = if_else(cell == "NOKS","NOKS","EBV"),
    cell = factor(cell,levels = c("EBV","NOKS")),
    condition = interaction(cell,treat) %>% 
      fct_relevel("EBV.MC","EBV.none","NOKS.MC","NOKS.none"))

fig5$alignment = fig5$alignment %>% 
  dplyr::rename(treat = treatment,
                replicate = rep) %>% 
  mutate(
    replicate = paste0("rep",replicate),
    treat = if_else(treat == "methyl","MC","none") %>% 
      factor(levels = c("MC","none")),
    cell = factor(cell,levels = c("EBV","NOKS","dRdZ")),
    condition = interaction(cell,treat) %>% 
      fct_relevel("EBV.MC","EBV.none","NOKS.MC","NOKS.none")
  )

rowVars <- function (x,na.rm = TRUE)
{
    sqr = function(x) x * x
    n = rowSums(!is.na(x))
    n[n <= 1] = NA
    return(rowSums(sqr(x - rowMeans(x,na.rm = na.rm)), na.rm = na.rm)/(n - 1))
}

biplot = function(env,cols = NULL,ntop = 500,x = 1,y = 2)
{
  rl = pluck(env,"rlogmat")  
  variances = rowVars(rl)  

  to_select = order(variances,decreasing = TRUE)[seq_len(min(ntop,length(variances)))]
  if(is.null(cols)){
    cols = colnames(rl)
  }
  pca = prcomp(t(rl[to_select,cols]))
  percentVar = pca$sdev^2/sum(pca$sdev^2)  

  plot_data = pluck(env,"alignment") %>% 
    dplyr::filter(file %in% cols) %>% 
    bind_cols(
      as.data.frame(pca$x) %>% 
        as_tibble()
    ) 
  
  plot_data %>% 
    ggplot(aes_string(paste0("PC",x) ,
                      paste0("PC",y),colour = "condition"))+
    geom_point()+
    xlab(paste0("PC",x,": ",round(percentVar[x] * 100), "% variance"))+
    ylab(paste0("PC",y,": ",round(percentVar[y] * 100), "% variance"))+
    scale_color_brewer(palette = "Dark2",name = "")+    
    geom_label_repel(aes(label = replicate),size = 4,
                     show.legend = FALSE)+
    coord_fixed()

}

nt = 1000

```

# PCA analysis old sample

```{r pca1,include=TRUE}

biplot(fig3,ntop = nt,x = 1,y = 2)
biplot(fig3,ntop = nt,x = 1,y = 3)
biplot(fig3,ntop = nt,x = 2,y = 3)

```

# PCA sample new sample

```{r pca2,include=TRUE}

biplot(fig5,ntop = nt,x = 1,y = 2)
biplot(fig5,ntop = nt,x = 1,y = 3)
biplot(fig5,ntop = nt,x = 2,y = 3)

```

## New sample without dRdZ

```{r pca3,include=TRUE}

cols = fig5$alignment %>% 
  dplyr::filter(cell != "dRdZ") %>% 
  pull(file)

biplot(fig5,cols = cols,ntop = nt,x = 1,y = 2)
biplot(fig5,cols = cols,ntop = nt,x = 1,y = 3)
biplot(fig5,cols = cols,ntop = nt,x = 2,y = 3)


```

# Correlation matrices

## Old sample

```{r corr_fun,include=FALSE,eval=TRUE}

quantile_breaks <- function(xs, n = 10,xmin = .4) {
  
  breaks <- quantile(xs, probs = seq(0, 1, length.out = n))
  breaks <- breaks[!duplicated(breaks)]
  if(!any(breaks < xmin)){
    breaks = c(xmin,breaks)
  }
  breaks
}

corr_matrix = function(env,cols = NULL,ntop = 500,unit = "rlog")
{
  if(unit == "rlog"){
    rl = pluck(env,"rlogmat")  
  }else if(unit == "tpm"){
    rl = pluck(env,"rsem_data") %>% 
      dplyr::select(file,rsem) %>% 
      unnest() %>% 
      dplyr::select(gene_id,file,TPM) %>% 
      spread(file,TPM) %>% 
      as.data.frame() %>% 
      tibble::column_to_rownames("gene_id") %>% 
      as.matrix()
  }
  variances = rowVars(rl)
  to_select = order(variances,decreasing = TRUE)[seq_len(min(ntop,length(variances)))]
  if(is.null(cols)){
    cols = colnames(rl)
  }
  
  mat = rl[to_select,cols]
  mat_cor = cor(mat)

  annots = env %>% 
    pluck("alignment") %>% 
    mutate(
      ff = paste(as.character(condition),
                 replicate,sep = "-")
    ) %>% 
    dplyr::filter(file %in% cols) %>% 
    dplyr::select(condition,ff)
  nms = annots %>% pull(ff)

  annots = annots %>%
    as.data.frame() %>% 
    tibble::column_to_rownames("ff")
  
  rownames(mat_cor) <- colnames(mat_cor) <- nms
  
  lo = 11
  pal = brewer_pal(palette = "RdYlBu",direction = -1)(lo)
  
  nconds = pull(annots,condition) %>% levels() %>% length()
  
  annot_colors = list(
    condition = brewer_pal(palette = "Dark2")(nconds) %>% 
      set_names(
        pull(annots,condition) %>% levels()
      )
  )
  
  
  pheatmap(mat_cor,
           color = pal,
           breaks = seq(.4,1,length.out = lo),#quantile_breaks(mat_cor, n = lo),
           annotation_row = annots,
           annotation_col = annots,
           annotation_colors = annot_colors,
           cluster_rows = TRUE,
           cluster_cols = TRUE)  
}


```


```{r, include=TRUE,fig.width=7}
corr_matrix(fig3,ntop = nt)
corr_matrix(fig3,ntop = nt,unit = "tpm")
```


## New sample

```{r, include=TRUE,fig.width=7}
corr_matrix(fig5,ntop = nt)
corr_matrix(fig5,ntop = nt,unit = "tpm")
```
