---
title: "Untreated samples: NOKS+EBV vs NOKS"
output: 
  flexdashboard::flex_dashboard:
    mathjax: local
    theme: flatly
    storyboard: true
runtime: shiny
---

```{r setup,include=TRUE,echo = FALSE,eval =TRUE}

library(tidyverse)
library(d3heatmap)
library(viridis)
library(scales)

load("fig2data.RData")

# 
#   require(viridis)
#   require(scales)
#   require(ggplot2)
#   pal = viridis(1e3, option = "D")
#   
#   ggplot(DT,aes_string(xvar,yvar))+stat_binhex(bins = 140) +
#     scale_fill_gradientn(colours = pal,trans = "log10",
#                          labels = trans_format('log10',math_format(10^.x)),
#                          guide = guide_colourbar(title = NULL,
#                            barheight = unit(0.92,"npc"),
#                            barwidth = unit(0.01,"npc")))+
#     xlim(-sc,sc)+ylim(-sc,sc)+
#     xlab(opt$xlab)+ylab(opt$ylab)

```

Inputs {.sidebar}
-------------------------------------

This is a dashboard. The idea is to list all the plots that we spoke about in an interactive fashion. 

```{r}
# shiny inputs defined here

 numericInput('heattop', 'Heatmap top DE genes', 10,
                 min = 10, max = 50,step =5 )

```


 

### DT demo. Just a block adding the genes that are going to be in the heatmap

```{r}

heat_tpm <- reactive({
  genes = diff_genes %>% 
    arrange(padj) %>% 
    head(input$heattop) %>% 
    pluck("ensembl_id")
  
  tpm_mat %>% 
    filter(ensembl_id %in% genes) %>% 
    select(gene_id,contains("mono"))
})

div(
  DT::renderDataTable({
    DT::datatable(heat_tpm())
  }),style = "font-size:80%")
```
    

### Volcano plot

```{r}
```


### MA plot

```{r}

```


### TPM histogram?


```{r}
```




